name: Build & Test Docker Image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    
    - uses: actions/checkout@v7
    
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        load: true
        tags: liatrio-technical
    
    - name: Start Image
      run: docker run -d --rm -p 80:3000 --name liatrio-server liatrio-technical
    - name: Run Tests
      uses: maxbutevil/liatrio-actions/apprentice-action@master
    - name: Stop Image
      run: docker stop liatrio-server
    
    - name: Create Docker Tag Identifier
      id: tag
      run: echo "::set-output name=id::$(git rev-parse --short HEAD)"
    
    - name: Push to GHCR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.id }}
          
      
      