name: Build & Test Docker Image
on: ["workflow_dispatch"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: docker build -t liatrio-technical .
    - run: docker run -d --rm -p 80:3000 --name liatrio-server liatrio-technical
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
    - run: docker stop liatrio-server